- hosts: batchserver.markmcintyreastro.co.uk
  vars:
    srcdir: /mnt/e/dev/energy/Geohome_Integration
  tasks:
  - name: import variables 
    include_vars: aws-vars.yml

  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/loadconfig.py', dest: '{{destdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/geohome.py', dest: '{{destdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/getdata.sh', dest: '{{destdir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/geohome.service', dest: '{{destdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/installService.sh', dest: '{{destdir}}/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{destdir}}/', mode: '754', backup: yes }
  - name: Copy analysis files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/data_analysis.py', dest: '{{destdir}}/', mode: '644', backup: yes }
    - {src: '{{srcdir}}/analyse.sh', dest: '{{destdir}}/', mode: '754', backup: yes }

  - name: Check requirements
    shell: . ~/.bashrc && conda activate $HOME/miniconda3/envs/openhabstuff && pip install -r {{destdir}}/requirements.txt
    args:
      executable: /bin/bash  
